// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Dialogs: typeof import('./src/components/Dialogs.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IBiCardList: typeof import('~icons/bi/card-list')['default']
    IBxEdit: typeof import('~icons/bx/edit')['default']
    IIcOutlineInventory: typeof import('~icons/ic/outline-inventory')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiEdit: typeof import('~icons/mdi/edit')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IRiTodoLine: typeof import('~icons/ri/todo-line')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
  }
}

export { }
